version: '3.8'

services:
  # 1. Сервис Базы Данных (PostgreSQL)
  db:
    image: postgres:14-alpine
    container_name: lashes_db
    restart: always
    environment:
      # Переменные, которые БД использует для инициализации
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isken
    ports:
      # Опционально: проброс порта БД на хост (для локального подключения, например, через DBeaver)
      - "5432:5432"
    volumes:
      # Постоянное хранение данных, чтобы они не терялись при перезапуске контейнера
      - postgres_data:/var/lib/postgresql/data

  # 2. Сервис Приложения (Spring Boot)
  app:
    build: . # Инструкция для Docker: собери образ из текущей директории, используя Dockerfile
    container_name: lashes_app
    ports:
      # Проброс порта приложения: [порт на хосте]:[порт в контейнере]
      - "8080:8080"
    environment:
      # Настройки для подключения к БД
      # Важно: используйте имя сервиса 'db' как hostname
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: isken

      # Настройки для 'Забыл пароль' (SMTP) - замените на свои
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: iskenpubg@gmail.com
      SPRING_MAIL_PASSWORD: ujtvgyeyxgtpskrg

    depends_on:
      - db # Гарантируем, что БД запустится до приложения

# Определяем именованный том для хранения данных БД
volumes:
  postgres_data: